# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpcui.ui'
#
# Created: Wed Dec 28 16:58:48 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 350)
        MainWindow.setMinimumSize(QtCore.QSize(700, 350))
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setEnabled(True)
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.addr_frame = QtGui.QFrame(self.tab_5)
        self.addr_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.addr_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.addr_frame.setObjectName(_fromUtf8("addr_frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.addr_frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.addr_frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.addr_label = QtGui.QLabel(self.addr_frame)
        self.addr_label.setObjectName(_fromUtf8("addr_label"))
        self.horizontalLayout.addWidget(self.addr_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.addr_frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.bal_frame = QtGui.QFrame(self.tab_5)
        self.bal_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bal_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.bal_frame.setObjectName(_fromUtf8("bal_frame"))
        self.gridLayout = QtGui.QGridLayout(self.bal_frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bal_refresh_button = QtGui.QPushButton(self.bal_frame)
        self.bal_refresh_button.setObjectName(_fromUtf8("bal_refresh_button"))
        self.gridLayout.addWidget(self.bal_refresh_button, 1, 0, 1, 1)
        self.bal_label = QtGui.QLabel(self.bal_frame)
        self.bal_label.setObjectName(_fromUtf8("bal_label"))
        self.gridLayout.addWidget(self.bal_label, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.bal_frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.bal_frame)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.send_frame = QtGui.QFrame(self.tab_5)
        self.send_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.send_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.send_frame.setObjectName(_fromUtf8("send_frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.send_frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.send_amt_spin_box = QtGui.QSpinBox(self.send_frame)
        self.send_amt_spin_box.setAccelerated(True)
        self.send_amt_spin_box.setMaximum(999999999)
        self.send_amt_spin_box.setObjectName(_fromUtf8("send_amt_spin_box"))
        self.gridLayout_2.addWidget(self.send_amt_spin_box, 1, 1, 1, 1)
        self.send_addr_line_edit = QtGui.QLineEdit(self.send_frame)
        self.send_addr_line_edit.setText(_fromUtf8(""))
        self.send_addr_line_edit.setObjectName(_fromUtf8("send_addr_line_edit"))
        self.gridLayout_2.addWidget(self.send_addr_line_edit, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.send_frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.send_frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.send_button = QtGui.QPushButton(self.send_frame)
        self.send_button.setObjectName(_fromUtf8("send_button"))
        self.gridLayout_2.addWidget(self.send_button, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.send_frame)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.rpc_console_text_browser = QtGui.QTextBrowser(self.tab_6)
        self.rpc_console_text_browser.setObjectName(_fromUtf8("rpc_console_text_browser"))
        self.verticalLayout_3.addWidget(self.rpc_console_text_browser)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab_6)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.rpc_line_edit = QtGui.QLineEdit(self.tab_6)
        self.rpc_line_edit.setObjectName(_fromUtf8("rpc_line_edit"))
        self.horizontalLayout_2.addWidget(self.rpc_line_edit)
        spacerItem4 = QtGui.QSpacerItem(100, 10, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.clear_button = QtGui.QPushButton(self.tab_6)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.horizontalLayout_2.addWidget(self.clear_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "Receive Address:", None))
        self.addr_label.setText(_translate("MainWindow", "address here", None))
        self.bal_refresh_button.setText(_translate("MainWindow", "Refresh", None))
        self.bal_label.setText(_translate("MainWindow", "balance here", None))
        self.label_3.setText(_translate("MainWindow", "Current Balance:", None))
        self.send_addr_line_edit.setPlaceholderText(_translate("MainWindow", "Address Here", None))
        self.label_6.setText(_translate("MainWindow", "Amount (Satoshi)", None))
        self.label_4.setText(_translate("MainWindow", "Send To:", None))
        self.send_button.setText(_translate("MainWindow", "Send", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Wallet Features", None))
        self.label.setText(_translate("MainWindow", "RPC Command:", None))
        self.rpc_line_edit.setPlaceholderText(_translate("MainWindow", "Command {json-formatted args}", None))
        self.clear_button.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "RPC Editor", None))

